import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Footer from './Shared/Footer/Footer'
import Header from './Shared/Header/Header'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>First Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header />
      </main>
      <Footer />
    </div>
  )
}
